### ISSUE TITLE
Services don't work if a public method is present

### ISSUE THREAD

**Issue by flaviocordova** [berkesa/moleculer-java#21]
Apparently, I can't define public methods along Moleculer Actions.

Here's my problem: I have a service that queries a Customer spring repository and, Since the class has a list attribute (let's say, contacts), spring will lazily load these objects.

The problem is that a moleculer Actions are not transactional (even if I mark the class with @Transactional) so these lazy load of inner object won't work since the parent object is already detached from the jpa context, what might be the first problem.

The natural solution would be to define a transaction method to do the job, converting the JPA object to a map (using ObjectMapper) and then call it from the Action. However, once you define a public method in a service, all Action in it will stop working. They are correctly published, but when you call them you get an exception:

```
java.lang.NullPointerException
	at services.moleculer.service.LocalActionEndpoint.lambda$0(LocalActionEndpoint.java:90)
	at services.moleculer.service.ActionEndpoint.handler(ActionEndpoint.java:85)
	at services.moleculer.service.DefaultServiceRegistry.receiveRequest(DefaultServiceRegistry.java:642)
	at services.moleculer.transporter.Transporter.processReceivedMessage(Transporter.java:720)
	at services.moleculer.transporter.Transporter.processReceivedMessage(Transporter.java:668)
	at services.moleculer.transporter.Transporter.lambda$1(Transporter.java:654)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It will work fine if I create a new @Component, move the method to the new class and call it from the action.

**Comment by berkesa** [comment]
Thanks for the feedback! I'll see what the reason may be ...

**Comment by berkesa** [comment]
Please try version **1.2.13-SNAPSHOT**:
```xml
<dependency>
	<groupId>com.github.berkesa</groupId>
	<artifactId>moleculer-java</artifactId>
	<version>1.2.13-SNAPSHOT</version>
</dependency>
```
You may also need to add the snapshot repo URL to the pom.xml:
```xml
<repository>
	<id>snapshots-repo</id>
	<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	<releases>
		<enabled>false</enabled>
	</releases>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```
Thanks!

**Comment by berkesa** [comment]
If you see that this version has improved the situation, I will compile a final version of it.

**Comment by berkesa** [comment]
Dear @flaviocordova,
Sometime you have time, please try this trial/snapshot version.
Let me know if you have a problem with it, I'll try to help.

**Comment by berkesa** [comment]
I transferred the changes to the final release.
